name: Tests
permissions:
  pull-requests: write
  statuses: write
  checks: write
  contents: read
  actions: read
on:
  push:
    branches: [master, ci]
  pull_request:
    branches: [master]
    types: [opened, reopened, synchronize]
  merge_group:
    types: [checks_requested]
jobs:
  tests:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Apt Packages
        id: cache-apt
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt
            /var/lib/apt/lists
          key: ${{ runner.os }}-apt-zsh-${{ hashFiles('.github/workflows/tests.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-zsh-

      - name: Install zsh
        run: |
          if ! command -v zsh >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends zsh
          else
            echo "zsh already installed"
          fi

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test
